### ISSUE TITLE
tests / instructions

### ISSUE THREAD

**Issue by danFromTelAviv** [eladhoffer/utils.pytorch#7]
Hi Elad - ma kore. 
I am trying to use the smooth cross entropy. I am not sure what exactly is the expected input. Can you add some rough doc or an example, please? 
Thanks,
Dan

**Comment by eladhoffer** [comment]
simply pass the smoothing coefficient as smooth_eps as in:
https://github.com/eladhoffer/seq2seq.pytorch/blob/master/seq2seq/tools/trainer.py#L123
